services:
    get_set_method_normalizer:
        class: Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer
        tags:
            - { name: serializer.normalizer }
#    visita_yucatan.example:
#        class: VisitaYucatanBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    visita_yucatan.locale_listener:
        class: VisitaYucatanBundle\EventListener\LocaleListener
        arguments: ['%kernel.default_locale%']
        tags:
        - { name: kernel.event_subscriber }
