services:
    get_set_method_normalizer:
        class: Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer
        tags:
            - { name: serializer.normalizer }
#    visita_yucatan.example:
#        class: VisitaYucatanBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
