visita_yucatan:
    resource: "@VisitaYucatanBundle/Resources/config/routing.yml"
    prefix:   annotation

app:
    resource: "@VisitaYucatanBundle/Controller/"
    type:     annotation

#Entra aqui cuando no encuentra alguna direccion
pageNotFound:
    pattern:  /{path}
    defaults: { _controller: VisitaYucatanBundle:Home:pageNotFound, path: '' }
    requirements:
        path: .*