<?php

namespace VisitaYucatanBundle\Repository;

/**
 * ArticuloIdiomaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticuloIdiomaRepository extends \Doctrine\ORM\EntityRepository {
}
