<?php

namespace VisitaYucatanBundle\Repository;

/**
 * ArticuloImagenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticuloImagenRepository extends \Doctrine\ORM\EntityRepository{
}
