<?php

namespace VisitaYucatanBundle\Repository;

/**
 * ArticuloImagenIdiomaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticuloImagenIdiomaRepository extends \Doctrine\ORM\EntityRepository
{
}
