<?php

namespace VisitaYucatanBundle\Repository;

/**
 * ConfigurationVarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigurationVarRepository extends \Doctrine\ORM\EntityRepository
{
}
