<?php

namespace VisitaYucatanBundle\Repository;

/**
 * DatospersonalesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatospersonalesRepository extends \Doctrine\ORM\EntityRepository
{
}
