<?php

namespace VisitaYucatanBundle\Repository;
use VisitaYucatanBundle\Entity\DatosVuelo;
use VisitaYucatanBundle\utils\DateUtil;
use VisitaYucatanBundle\utils\to\VentaCompletaTO;

/**
 * DatosVueloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatosVueloRepository extends \Doctrine\ORM\EntityRepository {
    
    public function createDatosVuelo(VentaCompletaTO $ventaCompletaTO){
        $datosVuelo = new DatosVuelo();
        $datosVuelo->setAerolinea($ventaCompletaTO->getAerolinea());
        $datosVuelo->setNumeroVuelo($ventaCompletaTO->getNumeroVuelo());
        $datosVuelo->setFechaLlegada(new \DateTime(DateUtil::formatDateMysql($ventaCompletaTO->getFechaLlegada())));
        $datosVuelo->setHoraLlegada(new \DateTime (date("H:i", strtotime($ventaCompletaTO->getHoraLlegada()))));

        return $datosVuelo;
    }
}
