<?php

namespace VisitaYucatanBundle\Repository;
use VisitaYucatanBundle\Entity\DatosVuelo;
use VisitaYucatanBundle\utils\to\VentaCompletaTO;

/**
 * DatosVueloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatosVueloRepository extends \Doctrine\ORM\EntityRepository {
    
    public function createDatosVuelo(VentaCompletaTO $ventaCompletaTO){
        $datosVuelo = new DatosVuelo();
        $datosVuelo->setAerolinea($ventaCompletaTO->getAerolinea());
        $datosVuelo->setNumeroVuelo($ventaCompletaTO->getNumeroVuelo());
        $datosVuelo->setFechaLlegada($ventaCompletaTO->getFechaLlegada());
        $datosVuelo->setHoraLlegada($ventaCompletaTO->getHoraLlegada());
    }
}
