<?php

namespace VisitaYucatanBundle\Repository;

/**
 * DatosPagoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatosPagoRepository extends \Doctrine\ORM\EntityRepository
{
}
