<?php

namespace VisitaYucatanBundle\Repository;

/**
 * DatosHotelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatosHotelRepository extends \Doctrine\ORM\EntityRepository
{
}
