<?php

namespace VisitaYucatanBundle\Repository;

/**
 * DatosVueloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatosVueloRepository extends \Doctrine\ORM\EntityRepository
{
}
