<?php

namespace VisitaYucatanBundle\Repository;
use VisitaYucatanBundle\Entity\DatosReserva;
use VisitaYucatanBundle\utils\DateUtil;
use VisitaYucatanBundle\utils\Generalkeys;

/**
 * DatosReservaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatosReservaRepository extends \Doctrine\ORM\EntityRepository {
    
    public function createDataReserva($hotelPickUp, $checkIn, $checkOut){
        $dataReservation = new DatosReserva();
        $dataReservation->setHotelPickUp($hotelPickUp);
        $dataReservation->setCheckIn(new \DateTime(DateUtil::formatDateMysql($checkIn)));
        $dataReservation->setCheckOut(is_null($checkOut) ? $checkOut : new \DateTime(DateUtil::formatDateMysql($checkOut)));

        return $dataReservation;
    }
}
