<?php

namespace VisitaYucatanBundle\Repository;
use VisitaYucatanBundle\Entity\Datospersonales;
use VisitaYucatanBundle\utils\to\VentaCompletaTO;

/**
 * DatospersonalesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatospersonalesRepository extends \Doctrine\ORM\EntityRepository {

    public function createPersonalData(VentaCompletaTO $ventaCompletaTO) {
        $personalData = new Datospersonales();
        $personalData->setNombres($ventaCompletaTO->getNombres());
        $personalData->setApellidos($ventaCompletaTO->getApellidos());

        return $personalData;
    }
}
