<?php

namespace VisitaYucatanBundle\Repository;

/**
 * DatosLlegadaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatosLlegadaRepository extends \Doctrine\ORM\EntityRepository {
}
