<?php

namespace VisitaYucatanBundle\Repository;

/**
 * DatosubicacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatosubicacionRepository extends \Doctrine\ORM\EntityRepository
{
}
