<?php

namespace VisitaYucatanBundle\Repository;
use VisitaYucatanBundle\Entity\DatosReserva;

/**
 * DatosReservaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatosReservaRepository extends \Doctrine\ORM\EntityRepository {
    
    public function createDataReserva($hotelPickUp, $checkIn, $checkOut){
        $dataReservation = new DatosReserva();
        $dataReservation->setHotelPickUp($hotelPickUp);
        $dataReservation->setCheckIn(new \DateTime(DateUtil::stringToDate($checkIn)));
        $dataReservation->setCheckOut(new \DateTime(DateUtil::stringToDate($checkOut)));

        return $dataReservation;
    }
}
