<?php

namespace VisitaYucatanBundle\Repository;
use VisitaYucatanBundle\utils\Estatuskeys;

/**
 * DestinoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DestinoRepository extends \Doctrine\ORM\EntityRepository {

    public function findAllDestinos(){
        $em = $this->getEntityManager();
        $sql = "SELECT destino.*
                FROM destino
                WHERE destino.id_estatus =  :estatus ";
        $params['estatus'] = Estatuskeys::ESTATUS_ACTIVO;
        $stmt = $em->getConnection()->prepare($sql);
        $stmt->execute($params);
        return $stmt->fetchAll();
    }
}
