<?php

namespace VisitaYucatanBundle\Repository;

/**
 * EstadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadoRepository extends \Doctrine\ORM\EntityRepository {

    public function findAllStates()
    {
        $em = $this->getEntityManager();
        $sql = "SELECT estado.id, estado.nombre FROM estado";
        $stmt = $em->getConnection()->prepare($sql);
        $stmt->execute();
        return $stmt->fetchAll();
    }
}
