<?php

namespace VisitaYucatanBundle\Repository;

/**
 * HotelimagenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HotelimagenRepository extends \Doctrine\ORM\EntityRepository
{
}
