<?php

namespace VisitaYucatanBundle\Repository;

/**
 * HotelidiomaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HotelidiomaRepository extends \Doctrine\ORM\EntityRepository
{
}
