<?php

namespace VisitaYucatanBundle\Repository;
use Doctrine\ORM\EntityNotFoundException;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use VisitaYucatanBundle\Entity\Hotelimagen;
use VisitaYucatanBundle\utils\Estatuskeys;
use VisitaYucatanBundle\utils\Generalkeys;

/**
 * HotelimagenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HotelimagenRepository extends \Doctrine\ORM\EntityRepository {

    public function findHotelImagesByIdHotel($idHotel){
        return $this->findBy(array('hotel' => $idHotel, 'estatus' => Estatuskeys::ESTATUS_ACTIVO));
    }

    public function uploadHotelImage($originalName, $nameImage, $folio, $path, $tipoArchivo, $idHotel){
        if(! $this->existHotel($idHotel)){
            throw new EntityNotFoundException('El hotel con id ' . $idHotel . " no se encontro");
        }
        $em = $this->getEntityManager();

        $hotelImage = new Hotelimagen();
        $hotelImage->setNombre($nameImage);
        $hotelImage->setNombreoriginal($originalName);
        $hotelImage->setFolio($folio);
        $hotelImage->setPath($path);
        $hotelImage->setTipoarchivo($tipoArchivo);
        $hotelImage->setPrincipal(Generalkeys::BOOLEAN_FALSE);
        $hotelImage->setFechacreacion(new \DateTime());
        $hotelImage->setEstatus($em->getReference('VisitaYucatanBundle:Estatus', Estatuskeys::ESTATUS_ACTIVO));
        $hotelImage->setHotel($em->getReference('VisitaYucatanBundle:Hotel', $idHotel));

        $em->persist($hotelImage);
        $em->flush();
    }

    public function deleteImageHotel($idImageHotel){
        $em = $this->getEntityManager();
        $imageHoel = $this->find($idImageHotel);
        if(! $imageHoel){
            throw new EntityNotFoundException('El La imagen con id ' . $idImageHotel . " no se encontro");
        }
        if(! unlink($imageHoel->getPath())){
            throw new FileException('No se pudo eliminar la imagen '.$imageHoel->getNombreoriginal());
        }
        $imageHoel->setEstatus($em->getReference('VisitaYucatanBundle:Estatus', Estatuskeys::ESTATUS_INACTIVO));
        $em->persist($imageHoel);
        $em->flush();
    }

    public function setPrincipalImageHotel($idHotel, $idImageHotel){
        $imagesHotel =$this->findHotelImagesByIdHotel($idHotel);

        if(count($imagesHotel) <= Generalkeys::NUMBER_ZERO){
            throw new \Exception('No se encontraron imagenes para el hotel '.$idHotel);
        }
        $em = $this->getEntityManager();

        foreach($imagesHotel as $image){
            if($image->getId() == $idImageHotel){
                $image->setPrincipal(Generalkeys::BOOLEAN_TRUE);
            }else{
                $image->setPrincipal(Generalkeys::BOOLEAN_FALSE);
            }
            $em->persist($image);
            $em->flush();
        }
    }

    public function existHotel($id){
        $em = $this->getEntityManager();
        if($em->getRepository('VisitaYucatanBundle:Hotel')->find($id)){
            return Generalkeys::BOOLEAN_TRUE;
        }
        return Generalkeys::BOOLEAN_FALSE;
    }

    public function findNextFolio(){

        $sql = "SELECT MAX(hotel_imagen.folio) AS folio
				FROM hotel_imagen
				WHERE hotel_imagen.id_estatus=:estatusActivo LIMIT ".Generalkeys::NUMBER_ONE;
        try{

            $params['estatusActivo'] = Estatuskeys::ESTATUS_ACTIVO;

            $stmt = $this->getEntityManager()->getConnection()->prepare($sql);
            $stmt->execute($params);
            $result = $stmt->fetch();
            $folio = (int)$result['folio'];

            return ($folio + Generalkeys::NUMBER_ONE);

        } catch(\Doctrine\ORM\NoResultException $e){

            return Generalkeys::NOT_FOUND_FOLIO;
        }
    }
}
