<?php

namespace VisitaYucatanBundle\Repository;
use VisitaYucatanBundle\utils\Estatuskeys;

/**
 * HotelPlanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HotelPlanRepository extends \Doctrine\ORM\EntityRepository {

    public function findPlans(){
        $em = $this->getEntityManager();
        $sql = "SELECT hotel_plan.id, hotel_plan.descripcion
                FROM hotel_plan
                WHERE hotel_plan.id_estatus =  :estatus ";
        $params['estatus'] = Estatuskeys::ESTATUS_ACTIVO;
        $stmt = $em->getConnection()->prepare($sql);
        $stmt->execute($params);
        return $stmt->fetchAll();
    }
}
