<?php

namespace VisitaYucatanBundle\Repository;
use VisitaYucatanBundle\Entity\Hotelidioma;
use VisitaYucatanBundle\utils\Estatuskeys;
use VisitaYucatanBundle\utils\Generalkeys;

/**
 * HotelidiomaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HotelidiomaRepository extends \Doctrine\ORM\EntityRepository {
    public function findHotelByIdAndIdLanguage($idHotel, $idIdioma) {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
                        'SELECT hotelidioma
                        FROM VisitaYucatanBundle:Hotelidioma hotelidioma
                        WHERE hotelidioma.estatus = :estatusActivo
                        AND hotelidioma.hotel = :idHotel
                        AND hotelidioma.idioma = :idIdioma'
        )->setParameter('estatusActivo', Estatuskeys::ESTATUS_ACTIVO)->setParameter('idHotel', $idHotel)->setParameter('idIdioma', $idIdioma);

        return $query->getOneOrNullResult();
    }

    public function saveHotelLanguage($hotelIdiomaTO) {
        $em = $this->getEntityManager();
        $hotelIdioma = $this->findHotelByIdAndIdLanguage($hotelIdiomaTO->getIdHotel(), $hotelIdiomaTO->getIdIdioma());
        $isNew = Generalkeys::BOOLEAN_FALSE;
        if (is_null($hotelIdioma)) {
            $isNew = Generalkeys::BOOLEAN_TRUE;
            $hotelIdioma = new Hotelidioma();
            $hotelIdioma->setEstatus($em->getReference('VisitaYucatanBundle:Estatus', Estatuskeys::ESTATUS_ACTIVO));
            $hotelIdioma->setHotel($em->getReference('VisitaYucatanBundle:Hotel', $hotelIdiomaTO->getIdHotel()));
            $hotelIdioma->setIdioma($em->getReference('VisitaYucatanBundle:Idioma', $hotelIdiomaTO->getIdIdioma()));
        }
        $hotelIdioma->setNombrehotel($hotelIdiomaTO->getNombreHotel());
        $hotelIdioma->setDescripcion($hotelIdiomaTO->getDescripcion());

        $em->persist($hotelIdioma);
        $em->flush();

        return $isNew;
    }
}
