<?php

namespace VisitaYucatanBundle\Repository;
use VisitaYucatanBundle\utils\Estatuskeys;

/**
 * HotelcontactoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HotelcontactoRepository extends \Doctrine\ORM\EntityRepository {

    public function findContactoByIdHotel($idHotel) {
        $em = $this->getEntityManager();
        $sql = "SELECT datos_personales.nombres, datos_personales.apellidos, datos_ubicacion.email
                FROM hotel_contacto
                INNER JOIN datos_personales ON datos_personales.id = hotel_contacto.id_datospersonales
                INNER JOIN datos_ubicacion ON datos_ubicacion.id = hotel_contacto.id_datosubicacion
                WHERE hotel_contacto.id_hotel = :hotel
                AND hotel_contacto.id_estatus = :estatus";
        $params['estatus'] = Estatuskeys::ESTATUS_ACTIVO;
        $params['hotel'] = $idHotel;
        $stmt = $em->getConnection()->prepare($sql);
        $stmt->execute($params);
        return $stmt->fetchAll();
    }

    public function createHotelContacto($hotelContactoTO){

    }
}
