<?php

namespace VisitaYucatanBundle\Repository;

/**
 * HotelcontactoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HotelcontactoRepository extends \Doctrine\ORM\EntityRepository
{
}
