<?php

namespace VisitaYucatanBundle\Repository;

use VisitaYucatanBundle\utils\Estatuskeys;
use VisitaYucatanBundle\utils\Generalkeys;

/**
 * IdiomaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IdiomaRepository extends \Doctrine\ORM\EntityRepository{
    public function findAllLanguage(){
        $em = $this->getEntityManager();
        $sql = "SELECT idioma.id, idioma.abreviatura, idioma.descripcion
                FROM idioma
                WHERE idioma.id_estatus =  :estatus ";
        $params['estatus'] = Estatuskeys::ESTATUS_ACTIVO;
        $stmt = $em->getConnection()->prepare($sql);
        $stmt->execute($params);
        return $stmt->fetchAll();
    }

    public function getIdIdiomaByAbreviatura($abreviatura){
        $idioma = $this->findOneBy(array('abreviatura' => $abreviatura, 'estatus' => Estatuskeys::ESTATUS_ACTIVO));
        if(is_null($idioma)){
            return Generalkeys::IDIOMA_ESPANOL;
        }
        return $idioma->getId();
    }
}
