<?php

namespace VisitaYucatanBundle\Repository;
use Doctrine\ORM\EntityNotFoundException;
use VisitaYucatanBundle\Entity\Estatus;
use VisitaYucatanBundle\utils\Estatuskeys;

/**
 * MonedaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MonedaRepository extends \Doctrine\ORM\EntityRepository{

    public function findAllCurrency(){
        $em = $this->getEntityManager();
        $sql = "SELECT moneda.id, moneda.descripcion, moneda.simbolo, moneda.tipo_cambio AS tipoCambio
                FROM moneda
                WHERE moneda.id_estatus =  :estatus ";
        $params['estatus'] = Estatuskeys::ESTATUS_ACTIVO;
        $stmt = $em->getConnection()->prepare($sql);
        $stmt->execute($params);
        return $stmt->fetchAll();
    }

    public function createCurrency($currency){
        $em = $this->getEntityManager();
        $currency->setEstatus($em->getReference('VisitaYucatanBundle:Estatus', Estatuskeys::ESTATUS_ACTIVO));

        $em->persist($currency);
        $em->flush();
    }

    public function updateCurrency($currency){
        $em = $this->getEntityManager();
        $currencyUpdate = $em->getRepository("VisitaYucatanBundle:Moneda")->find($currency->getId());
        if(! $currencyUpdate){
            throw new EntityNotFoundException('La moneda con id '.$currency->getId()." no se encontro");
        }
        // Actualiza la informacion de la moneda
        $currencyUpdate->setDescripcion($currency->getDescripcion());
        $currencyUpdate->setSimbolo($currency->getSimbolo());
        $currencyUpdate->setTipoCambio($currency->getTipoCambio());

        $em->persist($currencyUpdate);
        $em->flush();
    }

    public function deleteCurrency($idCurrency){
        $em = $this->getEntityManager();
        $currency = $em->getRepository('VisitaYucatanBundle:Moneda')->find($idCurrency);
        if(! $currency){
            throw new EntityNotFoundException('La moneda con id '.$idCurrency." no se encontro");
        }
        $currency->setEstatus($em->getReference('VisitaYucatanBundle:Estatus', Estatuskeys::ESTATUS_INACTIVO));
        $em->persist($currency);
        $em->flush();
    }

}
