<?php

namespace VisitaYucatanBundle\Repository;

/**
 * PaginaimagendescripcionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaginaimagendescripcionRepository extends \Doctrine\ORM\EntityRepository
{
}
