<?php

namespace VisitaYucatanBundle\Repository;

/**
 * PaginaimagenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaginaimagenRepository extends \Doctrine\ORM\EntityRepository{
}
