<?php

namespace VisitaYucatanBundle\Repository;

/**
 * PaginadescripcionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaginadescripcionRepository extends \Doctrine\ORM\EntityRepository {
}
