<?php

namespace VisitaYucatanBundle\Repository;

/**
 * PaqueteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaqueteRepository extends \Doctrine\ORM\EntityRepository {
}
