<?php

namespace VisitaYucatanBundle\Repository;

/**
 * PaqueteIdiomaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaqueteIdiomaRepository extends \Doctrine\ORM\EntityRepository {
}
