<?php

namespace VisitaYucatanBundle\Repository;

/**
 * PaqueteItinerarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaqueteItinerarioRepository extends \Doctrine\ORM\EntityRepository {
}
