<?php

namespace VisitaYucatanBundle\Repository;

/**
 * PaqueteImagenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaqueteImagenRepository extends \Doctrine\ORM\EntityRepository {
}
