<?php

namespace VisitaYucatanBundle\Repository;

/**
 * PaqueteCombinacionHotelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaqueteCombinacionHotelRepository extends \Doctrine\ORM\EntityRepository {
}
