<?php

namespace VisitaYucatanBundle\Repository;

use VisitaYucatanBundle\utils\Estatuskeys;
use VisitaYucatanBundle\utils\Generalkeys;

/**
 * PaqueteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaqueteRepository extends \Doctrine\ORM\EntityRepository {

	public function getPaquetes($idIdioma, $idMoneda, $offset, $limit){
		$em = $this->getEntityManager();
		$sql = "SELECT paquete.id,paquete_idioma.descripcioncorta,paquete_idioma.descripcionlarga,paquete_idioma.incluye,paquete_idioma.descripcion AS nombrepaquete,
				paquete_imagen.path AS imagen,moneda.simbolo,
				(select min(paquete_combinacion_hotel.costosencillo)/moneda.tipo_cambio from paquete_combinacion_hotel where paquete_combinacion_hotel.id_paquete = paquete.id) as sencilla
				FROM paquete
				INNER JOIN paquete_idioma ON paquete.id = paquete_idioma.id_paquete AND paquete_idioma.id_estatus = :estatusActivo
				INNER JOIN idioma ON idioma.id = paquete_idioma.id_idioma AND idioma.id = :idioma AND idioma.id_estatus = :estatusActivo
				INNER JOIN moneda ON moneda.id = :moneda AND moneda.id_estatus = :estatusActivo
				LEFT JOIN paquete_imagen ON paquete.id = paquete_imagen.id_paquete AND paquete_imagen.id_estatus = :estatusActivo
				WHERE paquete.id_estatus = :estatusActivo
				AND paquete.promovido = TRUE
				ORDER BY sencilla LIMIT ". $limit ." OFFSET ".$offset;
		$params['estatusActivo'] = Estatuskeys::ESTATUS_ACTIVO;
		$params['idioma'] = $idIdioma;
		$params['moneda'] = $idMoneda;

		$stmt = $em->getConnection()->prepare($sql);
		$stmt->execute($params);
		return $stmt->fetchAll();
	}
}
