<?php

namespace VisitaYucatanBundle\Repository;

/**
 * TourOrigenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TourOrigenRepository extends \Doctrine\ORM\EntityRepository
{
}
