<?php

namespace VisitaYucatanBundle\Repository;
use VisitaYucatanBundle\utils\Estatuskeys;
use VisitaYucatanBundle\utils\Generalkeys;

/**
 * TouridiomaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TouridiomaRepository extends \Doctrine\ORM\EntityRepository {

    public function findTourByIdAndIdLanguage($idTour, $idIdioma){
        $em = $this->getEntityManager();
        $query = $em->createQuery(
                        'SELECT touridioma
                        FROM VisitaYucatanBundle:Touridioma touridioma
                        WHERE touridioma.estatus = :estatusActivo
                        AND touridioma.tour = :idTour
                        AND touridioma.idioma = :idIdioma'
        )->setParameter('estatusActivo', Estatuskeys::ESTATUS_ACTIVO)->setParameter('idTour', $idTour)->setParameter('idIdioma', $idIdioma);

        return $query->getOneOrNullResult();
    }
}
