<?php

namespace VisitaYucatanBundle\Repository;
use VisitaYucatanBundle\Entity\Tourimagen;

/**
 * TourimagenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TourimagenRepository extends \Doctrine\ORM\EntityRepository{
    public function uploadTourImage($originalName, $nameImage){
        $tourImage = new Tourimagen();
        $tourImage->setNombre($nameImage);
        $tourImage->setNombreoriginal($originalName);
    }
}
