<?php

namespace VisitaYucatanBundle\Repository;
use VisitaYucatanBundle\utils\Estatuskeys;
use VisitaYucatanBundle\utils\Generalkeys;

/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends \Doctrine\ORM\EntityRepository{

    public function existUser($user){
        $user = $this->findOneBy(array('username' => $user,'estatus' => Estatuskeys::ESTATUS_ACTIVO));
        if($user){
            return Generalkeys::RESPONSE_TRUE;
        }
        return Generalkeys::RESPONSE_FALSE;
    }

    public function findUserByUsernameAndPassword($user, $password){
        $user = $this->findOneBy(array('username' => $user,'password' => md5($password),'estatus' => Estatuskeys::ESTATUS_ACTIVO));
        return $user;
    }
}
