<?php

namespace VisitaYucatanBundle\Repository;
use VisitaYucatanBundle\Entity\Datospersonales;
use VisitaYucatanBundle\Entity\DatosReserva;
use VisitaYucatanBundle\Entity\Datosubicacion;
use VisitaYucatanBundle\Entity\DatosVuelo;
use VisitaYucatanBundle\Entity\Estatus;
use VisitaYucatanBundle\Entity\Idioma;
use VisitaYucatanBundle\Entity\Moneda;
use VisitaYucatanBundle\Entity\Venta;
use VisitaYucatanBundle\utils\Estatuskeys;
use VisitaYucatanBundle\utils\Generalkeys;
use VisitaYucatanBundle\utils\to\VentaCompletaTO;

/**
 * VentaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VentaRepository extends \Doctrine\ORM\EntityRepository {

    public function createSaleHotel(VentaCompletaTO $ventaCompletaTO){
        $em = $this->getEntityManager();

        $venta = new Venta();

        $personalData = $this->createPersonalData($ventaCompletaTO);
        $em->persist($personalData);
        $dataLocation = $this->createDataLocation($ventaCompletaTO);
        $em->persist($dataLocation);
        $dataReservation = $this->createDataReserva(null, $ventaCompletaTO->getCheckIn(), $ventaCompletaTO->getCheckOut());
        $em->persist($dataReservation);

        $venta->setDatosPersonales($personalData);
        $venta->setDatosUbicacion($dataLocation);
        $venta->setFechaVenta(new \DateTime());
        $venta->setEstatus(new Estatus(Estatuskeys::ESTATUS_ACTIVO));
        $venta->setIdioma(new Idioma($ventaCompletaTO->getIdIdioma()));
        $venta->setMoneda(new Moneda($ventaCompletaTO->getIdMoneda()));
        $venta->setTipoCambio($ventaCompletaTO->getTipoCambio());
        $venta->setSubtotal($ventaCompletaTO->getTotal()); //TODO recordar el el total se debe guardar en mxn, si esta en otra moneda convertir antes
        $venta->setTotal($ventaCompletaTO->getTotal());

        $em->persist($venta);
        $em->flush();

        $em->getRepository('VisitaYucatanBundle:VentaDetalle')->createVentaDetalle($ventaCompletaTO, Generalkeys::TIPO_PRODUCTO_HOTEL);
    }
    
    public function createPersonalData(VentaCompletaTO $ventaCompletaTO) {
        $personalData = new Datospersonales();
        $personalData->setNombres($ventaCompletaTO->getNombres());
        $personalData->setApellidos($ventaCompletaTO->getApellidos());

        return $personalData;
    }

    public function createDataLocation(VentaCompletaTO $ventaCompletaTO) {
        $dataLocation = new Datosubicacion();
        $dataLocation->setLada($ventaCompletaTO->getLada());
        $dataLocation->setTelefono($ventaCompletaTO->getTelefono());
        $dataLocation->setEmail($ventaCompletaTO->getEmail());
        $dataLocation->setCiudad($ventaCompletaTO->getCiudad());

        return $dataLocation;
    }

    public function createDataReserva($hotelPickUp, $checkIn, $checkOut){
        $dataReservation = new DatosReserva();
        $dataReservation->setHotelPickUp($hotelPickUp);
        $dataReservation->setCheckIn($checkIn);
        $dataReservation->setCheckOut($checkOut);
        
        return $dataReservation;
    }

    public function createDatosVuelo(VentaCompletaTO $ventaCompletaTO){
        $datosVuelo = new DatosVuelo();
        $datosVuelo->setAerolinea($ventaCompletaTO->getAerolinea());
        $datosVuelo->setNumeroVuelo($ventaCompletaTO->getNumeroVuelo());
        $datosVuelo->setFechaLlegada($ventaCompletaTO->getFechaLlegada());
        $datosVuelo->setHoraLlegada($ventaCompletaTO->getHoraLlegada());
    }
}