<?php

namespace VisitaYucatanBundle\Repository;
use VisitaYucatanBundle\Entity\Estatus;
use VisitaYucatanBundle\Entity\VentaDetalle;
use VisitaYucatanBundle\utils\Estatuskeys;
use VisitaYucatanBundle\utils\to\VentaCompletaTO;

/**
 * VentaDetalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VentaDetalleRepository extends \Doctrine\ORM\EntityRepository {

    public function createVentaDetalle (VentaCompletaTO $ventaCompletaTO, $tipoProducto) {
        $em = $this->getEntityManager();
        
        $ventaDetalle = new VentaDetalle();
        $ventaDetalle->setEstatus(new Estatus(Estatuskeys::ESTATUS_ACTIVO));
        $ventaDetalle->setTipoProducto($tipoProducto);
        $ventaDetalle->setSubtotal($ventaCompletaTO->getTotal());
        $ventaDetalle->setTotal($ventaCompletaTO->getTotal());
        $ventaDetalle->setNumeroAdultos($ventaCompletaTO->getNumeroAdultos());
        $ventaDetalle->setNumeroMenores($ventaCompletaTO->getNumeroMenores());
        $ventaDetalle->setCostoAdulto($ventaCompletaTO->getCostoAdulto());
        $ventaDetalle->setCostoMenor($ventaCompletaTO->getCostoMenor());

        $em->persist($ventaDetalle);
        $em->flush();
        
    }
}
